# Salila Text2SQL 评估配置文件 - 模拟模式（调整权重）
evaluation:
  name: "Text2SQL-Sakila-Evaluation-Mock-Adjusted"
  description: "基于Sakila数据库的Text2SQL系统评估（模拟模式，调整权重）"
  dataset_path: "../datasets/sakila_test.json"
  output_path: "../results/"
  log_level: "INFO"
  mock_mode: true  # 启用模拟模式
  
# 数据库配置（模拟模式下不会实际连接）
database:
  type: "mysql"
  connection_string: "mysql+pymysql://mock:mock@localhost:3306/sakila"
  test_db_name: "sakila_test"
  schema_path: "../../Data/sakila/ddl_statements.yaml"
  description_path: "../../Data/sakila/db_description.yaml"
  isolation_mode: false  # 模拟模式下禁用隔离

# Text2SQL系统配置
model:
  system_path: "../../Text2SQL/Sakila/05-text2sql-rag-v3-agent.py"
  max_retries: 2
  timeout: 15
  embedding_model: "text-embedding-3-large"
  llm_model: "gpt-4o-mini"

# 评估指标配置（调整权重，专注于可评估的指标）
metrics:
  execution_accuracy:
    enabled: false  # 模拟模式下禁用执行准确率
    weight: 0.0
    description: "SQL执行准确率（模拟模式下禁用）"
    
  syntax_accuracy:
    enabled: true
    weight: 0.5  # 提高语法正确率权重
    description: "SQL语法正确率"
    
  semantic_similarity:
    enabled: true
    weight: 0.4  # 保持语义相似度权重
    description: "语义相似度"
    threshold: 0.8
    
  retrieval_recall:
    enabled: true
    weight: 0.1  # 降低检索召回率权重
    description: "检索召回率"
    levels:
      - "table_level"
      - "column_level"
      - "key_column_level"

# RAG检索配置
retrieval:
  top_k_ddl: 3
  top_k_examples: 3
  top_k_descriptions: 5
  similarity_threshold: 0.7

# 报告配置
reporting:
  generate_html: true
  generate_json: true
  include_visualizations: true
  detailed_error_analysis: true 